spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shinkendo
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

application:
  security:
    jwt:
      secret-key: XksbXmLsdw3v9kGFcHyQG4waU9BlQvgpn5Tdo4Sns6V3QoiqrEVfxX0FhcEArA5g
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days